version = 1

; (Optional) This section provides global settings shared across all presets.
; If the same key is defined in a specific preset, it will override the value in this global section.
[*]
ctx-size = 131072
jinja = true
flash-attn = on

; If the key corresponds to an existing model on the server,
; this will be used as the default config for that model
[bartowski/Kwaipilot_KAT-Coder-V2.5-Dev-GGUF:Q4_K_M]
ctx-size = 131072
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
cache-type-k = q8_0
cache-type-v = q8_0

[unsloth/Qwen3.6-35B-A3B-GGUF:Q4_K_M]
ctx-size = 131072
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.00
cache-type-k = q8_0
cache-type-v = q8_0

[unsloth/gemma-4-12b-it-GGUF:Q8_K_XL]
ctx-size = 131072
temp = 1.0
top-p = 0.95
top-k = 64
